### ISSUE TITLE
Slightly off CI limits on glm logistic regression

### ISSUE THREAD

**Issue by ValeriaRolle** [NikNakk/forestmodel#12]
This is an incredible package, thank you very much for it.

I've just noticed a little difference between the CI I got in the plot, and the CI I got by doing it _by hand_.
I have written an example with mtcars:
```
# First the model
m1 <- glm(am ~ mpg, family = binomial, data = mtcars)

# OR and CI (0.95)

round(exp(cbind("Odds ratio" = coef(m1), confint.default(m1, level = 0.95))),2)

# Which results in:

            Odds ratio 2.5 % 97.5 %
(Intercept)       0.00  0.00   0.14
mpg               1.36  1.09   1.70

# With forest_model

> forest_model(m1, return_data = TRUE)$plot_data$forest_data
Warning: Ignoring unknown aesthetics: x
# A tibble: 2 x 14
  term_label variable    class   level level_no     n term        estimate std.error statistic p.value conf.low conf.high reference
  <chr>      <chr>       <chr>   <lgl> <lgl>    <int> <chr>          <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl> <lgl>    
1 mpg        mpg         numeric NA    NA          32 mpg            0.307     0.115      2.67 0.00751    0.122     0.587 FALSE    
2 NA         (Intercept) NA      NA    NA          NA (Intercept)   -6.60      2.35      -2.81 0.00498  -12.3      -2.77  FALSE 

# In the tibble, before doing the exp, is already different, and in the plot it is "1.36 (1.13, 1.80)"

```
![imagen](https://user-images.githubusercontent.com/25933309/45150250-b2bcdf80-b1cb-11e8-9cce-3a0ce92fe651.png)

It is not a big deal here, but in my real data the p value is less than 0.05 and the CI goes from less than 1 to more than one in the forest plot!
It am not being able to find out where you calculate the confident intervals so I can't figure out what could be doing this... Any idea?

**Comment by NikNakk** [comment]
Thanks for your feedback. 

The reason for the difference is that `forest_model` uses `broom::tidy` which in turn uses `confint`. `confint` is an S3 function with a number of methods, and as always for S3, chooses a method based on the class of the first argument. In this case, it chooses `stats:::confint.glm` which in effect is `MASS:::confront.glm`. This profiles the log-likelihood function for the model and then uses a cubic spline to estimate the confidence intervals. It’s quite different to the method used by `confront.default` which uses the variance-covariant matrix. 

As far as I understand, for logistic regression `confint.glm` uses the recommended method, so what you’re seeing in `forest_model` is tight. 

Out of interest, why were you using `confront.default` rather than just `confint`?

BW

Nick

**Comment by ValeriaRolle** [comment]
Wow, I absolutely didn't know, thank you very much! 

In fact I was adding and substracting 1.96*Std. Error, 

```
exp(summary(m1)$coefficients[1:2,1]+1.96*summary(m1)$coefficients[1:2,2] exp(summary(m1)$coefficients[1:2,1]-1.96*summary(m1)$coefficients[1:2,2])
```

that shows exactly the same result as confint.default. I saw that line on the internet and used that method just for asking here, since it was shorter than my usual method and it gave me the same result, I didn't even know it was ".default" until you pointed it... Now if you excuse me I have to go and correct three or four other works :D

Thank you for your time and knowledge!!

**Comment by NikNakk** [comment]
For your interest, there’s a blog post at http://sas-and-r.blogspot.com/2011/11/example-914-confidence-intervals-for.html?m=1 which gives some further info on the two. 

BW

Nick

**Comment by RL31** [comment]
Hi,
i'm doing a logit model on a large sample size (over 2 millions obs) and forest_model() ends with an error : "profiling has found a better solution, so original fit had not converged". 
I understand that this error results from using confint() instead of confint.default(). 
Indeed, same error appears with confint(mylogit) but none with confint.default(mylogit).
Is there a way to specify how calculate the CI using forest_model() ?
Thanks
Rémi

**Comment by NikNakk** [comment]
There isn't directly. It uses `broom::tidy` which uses `confint`. The best
way would be to take advantage of the way S3 method dispatch works in R.

For example, if your model is called `my_model`, you could do the following:

    class(my_model) <- c("myglm",class(my_model))
    confint.myglm <- confint.default

You should then find that `broom::tidy(my_model)` uses the
`confint.default` method, and so should the `forestmodel` package.

BW

Nick

**Comment by RL31** [comment]
Thanks a lot, it works ! 

Rémi
